Parameters:
  ServiceName:
    Type: String
  ImageIdentifier:
    Type: String
  ImageRepositoryType:
    Type: String
    Default: ECR
  Port:
    Type: String
  CPU:
    Type: String
    Default: 1024
  Memory:
    Type: String
    Default: 2048
Conditions:
  PrivateECR: !Equals
    - !Ref ImageRepositoryType
    - ECR
Resources:
  AccessRole:
    Type: AWS::IAM::Role
    Condition: PrivateECR
    Properties:
      AssumeRolePolicyDocument:
        Version: '2008-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - build.apprunner.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess
  AppRunner:
    Type: 'AWS::AppRunner::Service'
    Properties:
      InstanceConfiguration:
        Cpu: !Ref CPU
        Memory: !Ref Memory
      ServiceName: !Ref ServiceName
      SourceConfiguration:
        AuthenticationConfiguration:
          AccessRoleArn: !If
            - PrivateECR
            - !GetAtt
              - AccessRole
              - Arn
            - !Ref 'AWS::NoValue'
        AutoDeploymentsEnabled: false
        ImageRepository:
          ImageConfiguration:
            Port: !Ref Port
          ImageIdentifier: !Ref ImageIdentifier
          ImageRepositoryType: !Ref ImageRepositoryType
Outputs:
  ServiceUrl:
    Description: The App Runner URL
    Value: !GetAtt
      - AppRunner
      - ServiceUrl
  ServiceArn:
    Description: The App Runner Service Arn
    Value: !GetAtt
      - AppRunner
      - ServiceArn
  ServiceId:
    Description: The App Runner Service Id
    Value: !GetAtt
      - AppRunner
      - ServiceId
  Status:
    Description: The App Runner Status
    Value: !GetAtt
      - AppRunner
      - Status