name: Docker Build and Push
inputs:
  image_tag:
    description: 'The ECR Docker image tag'
    required: true
  aws_access_key:
    description: 'The AWS access key'
    required: true
  aws_secret_key:
    description: 'The AWS secret key'
    required: true
  aws_region:
    description: 'The AWS region'
    required: true
runs:
  using: "composite"
  steps:
    - name: Clone code repo
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws_access_key }}
        aws-secret-access-key: ${{ inputs.aws_secret_key }}
        aws-region: ${{ inputs.aws_region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: 5.x

    - id: determine_version
      name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        additionalArguments: /overrideconfig mode=Mainline

    - name: Set up JDK 1.17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: adopt

    - uses: DeLaGuardo/setup-graalvm@4.0
      with:
        graalvm: '22.0.0.2'
        java: 'java17'
        arch: 'amd64'

    - name: Install native-image component
      run: gu install native-image
      shell: bash

    - name: Checkstyle
      run: mvn --batch-mode checkstyle:check
      shell: bash
      working-directory: java

    - name: Install modules
      run: mvn --batch-mode install -DskipTests
      shell: bash
      working-directory: java

    - name: Test Backend
      run: mvn --batch-mode test
      shell: bash
      working-directory: java/quarkus-microservice

    - name: Test Shared Library
      run: mvn --batch-mode test
      shell: bash
      working-directory: java/microservice-utils

    - name: Build with Maven
      run: mvn --batch-mode package --file pom.xml -DskipTests
      shell: bash
      working-directory: java/quarkus-microservice

    - name: Generate JaCoCo Badges
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
        jacoco-csv-file: java/quarkus-microservice/target/jacoco-report/jacoco.csv
        coverage-badge-filename: quarkus-microservice.svg
        branches-badge-filename: quarkus-microservice-branches.svg

    - name: Generate JaCoCo Badges for Shared Library
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
        jacoco-csv-file: java/microservice-utils/target/site/jacoco/jacoco.csv
        coverage-badge-filename: microservice-utils.svg
        branches-badge-filename: microservice-utils-branches.svg

    - name: Commit the badges (if they changed)
      run: |
        if [[ `git diff --exit-code .github/badges` ]]; then
          git config --global user.name 'Matthew Casperson'
          git config --global user.email 'mcasperson@users.noreply.github.com'
          git add .github/badges/*
          git commit -m "Autogenerated JaCoCo coverage badge"
          git push || true
        fi
      shell: bash

    - name: Build, tag, and push image to Amazon ECR
      run: |
        docker build -f src/main/docker/Dockerfile.legacy-jar -t ${{ inputs.image_tag }} .
        docker push ${{ inputs.image_tag }}
      shell: bash
      working-directory: java/quarkus-microservice