name: Octopus Service Account creator
description: Deploys the Octopus Service Account creator
'on':
  workflow_dispatch: {}
  push: {}
inputs:
  octopus_server:
    description: "The Octopus server"
    required: true
  octopus_apikey:
    description: "The Octopus API token"
    required: true
  octopus_space_id:
    description: 'The ID of the app builder space'
    required: true
  octopus_application_lifecycle_id:
    description: 'The application deployment lifecycle'
    required: true
  octopus_development_environment_id:
    description: 'The development environment'
    required: true
  octopus_development_security_environment_id:
    description: 'The development security environment'
    required: true
  octopus_production_environment_id:
    description: 'The production environment'
    required: true
  octopus_production_security_environment_id:
    description: 'The production security environment'
    required: true
  octopus_built_in_feed_id:
    description: 'The built in feed ID'
    required: true
  octopus_content_team_maven_feed_id:
    description: 'The GitHub Repo hosted maven feed ID'
    required: true
  octopus_development_aws_account_id:
    description: 'The development AWS account id'
    required: true
  octopus_production_aws_account_id:
    description: 'The production AWS account id'
    required: true
  octopus_worker_pool_id:
    description: 'The worker pool id used for the deployment steps'
    required: true
  aws_access_key:
    description: 'The AWS access key'
    required: true
  aws_secret_key:
    description: 'The AWS secret key'
    required: true
  aws_region:
    description: 'The AWS region'
    required: true
  servicebus_secret_development:
    description: 'The service bus secret for Development'
    required: true
  servicebus_secret_production:
    description: 'The service bus secret for Production'
    required: true
  servicebus_tenant_development:
    description: 'The service bus tenant for Development'
    required: true
  servicebus_tenant_production:
    description: 'The service bus tenant for Production'
    required: true
  servicebus_namespace_development:
    description: 'The service bus namespace for Development'
    required: true
  servicebus_namespace_production:
    description: 'The service bus namespace for Production'
    required: true
  servicebus_application_id_development:
    description: 'The service bus app id for Development'
    required: true
  servicebus_application_id_production:
    description: 'The service bus app id for Production'
    required: true
  cognito_library_variable_set_id:
    description: 'The ID of the variable set containing shared cognito values'
    required: true
  content_team_library_variable_set_id:
    description: 'The ID of the variable set containing shared content team values'
    required: true
  github_actions_library_variable_set_id:
    description: 'The ID of the variable set containing github actions workflows values'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: '0'

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Install AWS CLI
      uses: unfor19/install-aws-cli-action@v1

    - name: Create Terraform state S3 bucket
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_key }}
      run: |
        # Check to see if the bucket exists
        aws s3api head-bucket --bucket app-builder-c81b45ae-50de-466c-8500-3845fd8b80c4 --region us-west-1 2>/dev/null
        # If not, create it
        if [[ $? -ne 0 ]]; then        
          aws s3 mb s3://app-builder-c81b45ae-50de-466c-8500-3845fd8b80c4 --region us-west-1
          sleep 60 
        fi
      shell: "bash -l {0}" # Allow commands to fail by removing the default "-e" argument

    - name: Terraform Init
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_key }}
        TF_INPUT: "0"
      run: terraform init
      working-directory: terraform/azure-servicebus-proxy
      shell: bash

    - name: Terraform Apply
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_key }}
        TF_INPUT: "0"
      run: >
        terraform apply 
        -auto-approve 
        -var="octopus_server=${{ inputs.octopus_server }}" 
        -var="octopus_apikey=${{ inputs.octopus_apikey }}"
        -var="octopus_space_id=${{ inputs.octopus_space_id }}"
        -var="octopus_application_lifecycle_id=${{ inputs.octopus_application_lifecycle_id }}"
        -var="aws_region=${{ inputs.aws_region }}"
        -var="octopus_development_aws_account_id=${{ inputs.octopus_development_aws_account_id }}"
        -var="octopus_production_aws_account_id=${{ inputs.octopus_production_aws_account_id }}"
        -var="octopus_worker_pool_id=${{ inputs.octopus_worker_pool_id }}"
        -var="octopus_built_in_feed_id=${{ inputs.octopus_built_in_feed_id }}"
        -var="octopus_content_team_maven_feed_id=${{ inputs.octopus_content_team_maven_feed_id }}"
        -var="octopus_development_environment_id=${{ inputs.octopus_development_environment_id }}"
        -var="octopus_development_security_environment_id=${{ inputs.octopus_development_security_environment_id }}"
        -var="octopus_production_environment_id=${{ inputs.octopus_production_environment_id }}"
        -var="octopus_production_security_environment_id=${{ inputs.octopus_production_security_environment_id }}"
        -var="servicebus_secret_development=${{ inputs.servicebus_secret_development }}"
        -var="servicebus_secret_production=${{ inputs.servicebus_secret_production }}"
        -var="servicebus_tenant_production=${{ inputs.servicebus_tenant_production }}"
        -var="servicebus_tenant_development=${{ inputs.servicebus_tenant_development }}"
        -var="servicebus_namespace_production=${{ inputs.servicebus_namespace_production }}"
        -var="servicebus_namespace_development=${{ inputs.servicebus_namespace_development }}"
        -var="servicebus_application_id_production=${{ inputs.servicebus_application_id_production }}"
        -var="servicebus_application_id_development=${{ inputs.servicebus_application_id_development }}"
        -var="cognito_library_variable_set_id=${{ inputs.cognito_library_variable_set_id }}"
        -var="content_team_library_variable_set_id=${{ inputs.content_team_library_variable_set_id }}"
        -var="github_actions_library_variable_set_id=${{ inputs.github_actions_library_variable_set_id }}"
      working-directory: terraform/azure-servicebus-proxy
      shell: bash