trigger:
  branches:
    include:
    - main
    - master
  paths:
    include:
      - java/**/*
      - systemd/java-microservice/*
      - azure-devops/java-microservice/*

pool:
  vmImage: ubuntu-latest

parameters:
  - name: OctopusServer
    displayName: The name of the Octopus connection
    default: Octopus
    type: string
  - name: OctopusSpace
    displayName: The ID of the Octopus space
    default: 'Spaces-1370'
    type: string
  - name: OctopusProject
    displayName: The ID of the Octopus project
    default: 'Projects-3448'
    type: string

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: build_app
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Bash@3
            displayName: "Populate Local Maven Repo"
            inputs:
              targetType: inline
              script: |
                # Download and extract a local maven repo cache. This speeds up build times.
                # Regenerate this by doing a "./mvnw install" and then "7z a repository.7z -r repository"                
                curl https://octopus-sales-engineering.s3.ap-southeast-2.amazonaws.com/repository.7z -o ~/repository.7z
                mkdir -p ~/.m2
                cd ~/.m2
                7z x -aoa ~/repository.7z
          - task: Bash@3
            displayName: "Install Libraries"
            inputs:
              targetType: inline
              script: ./mvnw clean install --batch-mode -DskipTests
              workingDirectory: java
          - task: Bash@3
            displayName: "Build Application"
            inputs:
              targetType: inline
              script: ./mvnw clean package --batch-mode -DskipTests
              workingDirectory: java/products-microservice
          - publish: './java/products-microservice/target/products-microservice-runner.jar'
            displayName: 'Capture Artifacts'
            artifact: javaJar
  - stage: DevelopmentDeploy
    displayName: Deploy to Development
    jobs:
      - deployment: DeployWeb
        displayName: Deploy Web App
        environment:
          name: Development
          resourceType: VirtualMachine
          tags: web
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: systemd-deployment.yaml
  - stage: TestDeploy
    displayName: Deploy to Test
    jobs:
      - job: ManualApprovalTest
        displayName: "Manual Approval"
        pool: server
        steps:
          - task: ManualValidation@0
            inputs:
              notifyUsers: matthew.casperson@octopus.com
              instructions: Allow the deployment to progress to the Test environment?
              onTimeout: 'reject'
      - deployment: DeployWeb
        displayName: Deploy Web App
        dependsOn: ManualApprovalTest
        environment:
          name: Test
          resourceType: VirtualMachine
          tags: web
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: systemd-deployment.yaml
  - stage: ProductionDeploy
    displayName: Deploy to Production
    jobs:
      - job: ManualApprovalProd
        displayName: "Manual Approval"
        pool: server
        steps:
          - task: ManualValidation@0
            inputs:
              notifyUsers: matthew.casperson@octopus.com
              instructions: Allow the deployment to progress to the Production environment?
              onTimeout: 'reject'
      - deployment: DeployWeb
        displayName: Deploy Web App
        dependsOn: ManualApprovalProd
        environment:
          name: Production
          resourceType: VirtualMachine
          tags: web
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: systemd-deployment.yaml