name: app-runner

on:
  push:
    paths:
      - '.github/workflows/<%= cloudformation_stack_name %>.yml'
      - 'terraform/<%= cloudformation_stack_name %>/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build
        uses: ./terraform/app-runner
        with:
          aws_access_key: <%= aws_access_key %>
          aws_secret_key: <%= aws_secret_key %>
          octopus_server: <%= octopus_server %>
          octopus_apikey: <%= octopus_apikey %>
          octopus_space_id: <%= octopus_space_id %>
          octopus_development_environment_id: <%= octopus_development_environment_id %>
          octopus_production_environment_id: <%= octopus_production_environment_id %>
          octopus_development_security_environment_id: <%= octopus_development_security_environment_id %>
          octopus_production_security_environment_id: <%= octopus_production_security_environment_id %>
          octopus_project_name: <%= octopus_project_name %>
          octopus_project_group_name: <%= octopus_project_group_name %>
          octopus_lifecycle_id: <%= octopus_lifecycle_id %>
          docker_image: <%= docker_image %>
          docker_port: <%= docker_port %>
          octopus_aws_development_account_id: <%= octopus_aws_development_account_id %>
          octopus_aws_production_account_id: <%= octopus_aws_production_account_id %>
          aws_region: <%= aws_region %>
          terraform_bucket_suffix: <%= terraform_bucket_suffix %>
          octopus_ecr_feed_name: <%= octopus_ecr_feed_name %>
          cloudformation_stack_name: <%= cloudformation_stack_name %>
          apprunner_service_name: <%= apprunner_service_name %>

