name: 'Microservice Utils'
description: Build and deploy the Jenkins Pipeline Backend
inputs:
  github_token:
    required: true
    description: The github token
runs:
  using: "composite"
  steps:
    # See https://github.com/actions/checkout/issues/124#issuecomment-606277160 for why we use
    # fetch-depth
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: nelonoel/branch-name@v1.0.1

    - name: Set up JDK 1.17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: List dependencies
      run: mvn --batch-mode dependency:tree --no-transfer-progress
      shell: bash
      working-directory: java/microservice-utils

    - name: Test Backend
      run: mvn --batch-mode --no-transfer-progress test
      shell: bash
      working-directory: java/microservice-utils

    - name: Generate JaCoCo Badges
      if: ${{ env.BRANCH_NAME == 'main' }}
      id: jacocoMod1
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
        jacoco-csv-file: java/microservice-utils/target/site/jacoco/jacoco.csv
        coverage-badge-filename: microservice-utils-coverage.svg
        branches-badge-filename: microservice-utils-branches.svg

    - name: Update resources
      if: ${{ env.BRANCH_NAME == 'main' }}
      uses: test-room-7/action-update-file@v1.6.0
      with:
        file-path: |
          .github/badges/microservice-utils-coverage.svg
          .github/badges/microservice-utils-branches.svg
        commit-msg: Update badges
        github-token: ${{ inputs.github_token }}