FROM public.ecr.aws/lambda/nodejs:14

# Assumes your function is named "app.js", and there is a package.json file in the app directory
COPY . ${LAMBDA_TASK_ROOT}

# Install NPM dependencies for function
RUN npm install

# Build the
RUN npm run build

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "dist/application/lambda/generate-template.lambdaHandler" ]