name: 'Jenkins Pipeline Backend'
inputs:
  dockerhub_username:  
    required: true
  dockerhub_password:  
    required: true
  github_token:  
    required: true
  octopus_server_url:  
    required: true
  octopus_api_token:  
    required: true
  run_number:  
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_password }}

    - uses: nelonoel/branch-name@v1.0.1

    - name: Install Octopus CLI
      uses: OctopusDeploy/install-octopus-cli-action@v1.1.1
      with:
        version: latest

    - name: Set up JDK 1.17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - uses: DeLaGuardo/setup-graalvm@4.0
      with:
        graalvm: '22.0.0.2'
        java: 'java17'
        arch: 'amd64'

    - name: Install native-image component
      run: gu install native-image
      shell: bash

    - name: Checkstyle
      run: mvn --batch-mode checkstyle:check
      shell: bash
      working-directory: java

    - name: Install modules
      run: mvn --batch-mode install -DskipTests
      shell: bash
      working-directory: java

    - name: Update version
      run: mvn --batch-mode build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.incrementalVersion}.${{ github.run_number }}
      shell: bash
      working-directory: java/jenkins-pipeline-builder-github-backend

    - name: List dependencies
      run: mvn --batch-mode dependency:tree --no-transfer-progress
      shell: bash
      working-directory: java/jenkins-pipeline-builder-github-backend

    - name: Build with Maven
      run: mvn --batch-mode package --file pom.xml -Pnative -DskipTests
      shell: bash
      working-directory: java/jenkins-pipeline-builder-github-backend

    - name: Test Backend
      run: mvn --batch-mode test
      shell: bash
      working-directory: java/jenkins-pipeline-builder-github-backend

    - name: Test Pipelines
      run: mvn --batch-mode test
      shell: bash
      working-directory: java/jenkins-pipeline-builder

    - name: Test Common
      run: mvn --batch-mode test
      shell: bash
      working-directory: java/pipeline-builder-utils

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        tag_name: jenkins-pipeline-backend.0.1.${{ inputs.run_number }}
        release_name: Jenkins Pipeline Backend Release 0.1.${{ inputs.run_number }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: java/jenkins-pipeline-builder-github-backend/target/jenkins-pipeline-builder-github-backend-runner
        asset_name: jenkins-pipeline-builder-github-backend-runner
        asset_content_type: application/octet-stream

    - name: Rename zip
      run: >
        mv jenkins-pipeline-builder-github-backend/target/function.zip
        jenkins-pipeline-builder-github-backend-lambda.0.1.0.${{ inputs.run_number }}.zip
      shell: bash
      working-directory: java

    - name: Push Package
      run: >
        octo push --package jenkins-pipeline-builder-github-backend-lambda.0.1.0.${{ inputs.run_number }}.zip
        --server ${{ inputs.octopus_server_url }}
        --apiKey ${{ inputs.octopus_api_token }}
        --space "Content Team"
      shell: bash
      working-directory: java

    - name: Generate SBOM
      run: mvn cyclonedx:makeAggregateBom -DskipTests
      shell: bash
      working-directory: java

    - name: Build SBOM package
      run: >
        octo pack
        --id jenkins-pipeline-builder-github-backend-lambda-sbom
        --version 0.1.0.${{ inputs.run_number }}
        --format zip
        --include **/bom.xml
      shell: bash
      working-directory: java

    - name: Push SBOM Package
      run: >
        octo push --package jenkins-pipeline-builder-github-backend-lambda-sbom.0.1.0.${{ inputs.run_number }}.zip
        --server ${{ inputs.octopus_server_url }}
        --apiKey ${{ inputs.octopus_api_token }}
        --space "Content Team"
      shell: bash
      working-directory: java

    - name: Trigger deployment
      run: >
        octo create-release
        --gitRef "main"
        --project "Jenkins Pipeline Generator"
        --deployTo "Development"
        --server ${{ inputs.octopus_server_url }}
        --apiKey ${{ inputs.octopus_api_token }}
        --waitForDeployment 
        --space "Content Team"
        --deploymentTimeout 00:30:00
      shell: bash

    - name: Trigger deployment to security environment
      run: >
        octo deploy-release
        --project "Jenkins Pipeline Generator"
        --deployTo "Development (Security)"
        --server ${{ inputs.octopus_server_url }}
        --apiKey ${{ inputs.octopus_api_token }}
        --space "Content Team"
        --version=latest
      shell: bash