name: <%= project_name %>

on:
  push:
    paths:
      - '.github/workflows/<%= project_name %>.yaml'
      - 'terraform/<%= project_name %>/**'
      - 'github/<%= project_name %>/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build
        uses: ./github/<%= project_name %>
        with:
          project_name: <%= project_name %>
          project_directory_name: <%= project_name %>
          octopus_server: <%= octopus_server %>
          octopus_apikey: <%= octopus_apikey %>
          octopus_space_id: <%= octopus_space_id %>
          octopus_dockerhub_feed_id: <%= octopus_dockerhub_feed_id %>
          octopus_application_lifecycle_id: <%= octopus_application_lifecycle_id %>
          octopus_simple_lifecycle_id: <%= octopus_simple_lifecycle_id %>
          octopus_production_only_lifecycle_id: <%= octopus_production_only_lifecycle_id %>
          octopus_development_app_environment_id: <%= octopus_development_app_environment_id %>
          octopus_development_security_environment_id: <%= octopus_development_security_environment_id %>
          octopus_production_app_environment_id: <%= octopus_production_app_environment_id %>
          octopus_production_security_environment_id: <%= octopus_production_security_environment_id %>
          github_package_pat: <%= github_package_pat %>
          namespace_prefix: '<%- namespace_prefix %>'

          # AWS vars
          aws_access_key: <%= aws_access_key %>
          aws_secret_key: <%= aws_secret_key %>
          aws_region: <%= aws_region %>