name: 'GitHub OAuth Backend'
description: Build and deploy the GitHub OAuth Backend
inputs:
  dockerhub_username:
    required: true
    description: The DockerHub username
  dockerhub_password:
    required: true
    description: The DockerHub password
  github_token:
    required: true
    description: The GitHub token
  octopus_server_url:
    required: true
    description: The Octopus server
  octopus_api_token:
    required: true
    description: The Octopus API key
  run_number:
    required: true
    description: The GitHub Actions run number
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_password }}

    - uses: nelonoel/branch-name@v1.0.1

    - name: Install Octopus CLI
      uses: OctopusDeploy/install-octopus-cli-action@v1.1.1
      with:
        version: latest

    - name: Set up JDK 1.11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Checkstyle
      run: mvn --batch-mode checkstyle:check
      shell: bash
      working-directory: java

    - name: Install modules
      run: mvn --batch-mode install -DskipTests
      shell: bash
      working-directory: java

    - name: Update version
      run: mvn --batch-mode build-helper:parse-version versions:set -DnewVersion=1.0.${{ github.run_number }}
      shell: bash
      working-directory: java/azure-servicebus-proxy

    - name: List dependencies
      run: mvn --batch-mode dependency:tree --no-transfer-progress
      shell: bash
      working-directory: java/azure-servicebus-proxy

    # Note that we build a regular Java app here rather than a GraalVM native executable.
    # This is because the Azure SDK didn't work with native builds.
    - name: Build with Maven
      run: ./mvnw --batch-mode clean package --file pom.xml -Plambda -DskipTests "-Dquarkus.profile=prod"
      shell: bash
      working-directory: java/azure-servicebus-proxy

    - name: Rename zip
      run: >
        mv azure-servicebus-proxy/target/function.zip
        azure-servicebus-proxy-lambda.1.0.${{ inputs.run_number }}.zip
      shell: bash
      working-directory: java

    - name: Push Package
      run: >
        octo push --package azure-servicebus-proxy-lambda.1.0.${{ inputs.run_number }}.zip
        --server ${{ inputs.octopus_server_url }}
        --apiKey ${{ inputs.octopus_api_token }}
        --overwrite-mode OverwriteExisting 
        --use-delta-compression false
        --space "Content Team"
      shell: bash
      working-directory: java

    - name: Test Backend
      run: mvn --batch-mode test
      shell: bash
      working-directory: java/azure-servicebus-proxy

    - name: Generate JaCoCo Badges
      id: jacocoMod1
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
        jacoco-csv-file: java/azure-servicebus-proxy/target/jacoco-report/jacoco.csv
        coverage-badge-filename: azure-servicebus-proxy-coverage.svg
        branches-badge-filename: azure-servicebus-proxy-branches.svg

    - name: Update resources
      if: ${{ env.BRANCH_NAME == 'main' }}
      uses: test-room-7/action-update-file@v1.6.0
      with:
        file-path: |
          .github/badges/azure-servicebus-proxy-coverage.svg
          .github/badges/azure-servicebus-proxy-branches.svg
        commit-msg: Update badges
        github-token: ${{ inputs.github_token }}

    - name: Test Common
      run: mvn --batch-mode test
      shell: bash
      working-directory: java/azure-servicebus-proxy

    - name: Generate SBOM
      run: mvn cyclonedx:makeAggregateBom -DskipTests --no-transfer-progress --batch-mode
      shell: bash
      working-directory: java

    - name: Build SBOM package
      run: >
        octo pack
        --id azure-servicebus-proxy-lambda-sbom
        --version 1.0.${{ inputs.run_number }}
        --format zip
        --include **/bom.xml
      shell: bash
      working-directory: java

    - name: Push SBOM Package
      run: >
        octo push 
        --package azure-servicebus-proxy-lambda-sbom.1.0.${{ inputs.run_number }}.zip
        --server ${{ inputs.octopus_server_url }}
        --apiKey ${{ inputs.octopus_api_token }}
        --space "Content Team"
      shell: bash
      working-directory: java

    - name: Generate Octopus Deploy build information
      uses: xo-energy/action-octopus-build-information@v1.1.2
      with:
        octopus_api_key: ${{ inputs.octopus_api_token }}
        octopus_project: GitHub Actions Azure Service Bus Proxy
        octopus_server: ${{ inputs.octopus_server_url }}
        octopus_space: Content Team
        push_version: 1.0.${{ inputs.run_number }}
        push_package_ids: github-oauth-backend-lambda
        push_overwrite_mode: OverwriteExisting
        output_path: octopus

    - name: Trigger deployment
      if: ${{ env.BRANCH_NAME == 'main' }}
      run: >
        octo create-release
        --project "GitHub Actions Azure Service Bus Proxy"
        --version 1.0.${{ inputs.run_number }}
        --deployTo "Development"
        --server ${{ inputs.octopus_server_url }}
        --apiKey ${{ inputs.octopus_api_token }}
        --space "Content Team"
        --waitForDeployment
        --deploymentTimeout 00:30:00
      shell: bash

    - name: Trigger deployment to security environment
      if: ${{ env.BRANCH_NAME == 'main' }}
      run: >
        octo promote-release
        --project "GitHub Actions Azure Service Bus Proxy"
        --from "Development"
        --deployTo "Development (Security)"
        --server ${{ inputs.octopus_server_url }}
        --apiKey ${{ inputs.octopus_api_token }}
        --space "Content Team"
        --latestSuccessful
      shell: bash


    - name: Trigger deployment
      if: ${{ env.BRANCH_NAME == 'main' }}
      run: >
        octo create-release
        --project "Jenkins Pipelines Azure Service Bus Proxy"
        --deployTo "Development"
        --version 1.0.${{ inputs.run_number }}
        --server ${{ inputs.octopus_server_url }}
        --apiKey ${{ inputs.octopus_api_token }}
        --space "Content Team"
        --waitForDeployment
        --deploymentTimeout 00:30:00
      shell: bash

    - name: Trigger deployment to security environment
      if: ${{ env.BRANCH_NAME == 'main' }}
      run: >
        octo promote-release
        --project "Jenkins Pipelines Azure Service Bus Proxy"
        --from "Development"
        --version 1.0.${{ inputs.run_number }}
        --deployTo "Development (Security)"
        --server ${{ inputs.octopus_server_url }}
        --apiKey ${{ inputs.octopus_api_token }}
        --space "Content Team"
        --latestSuccessful
      shell: bash