version: "3.9"
services:
  frontend:
    image: "octopussamples/workflowbuilderfrontend"
    ports:
      - "5000:5000"
  templategenerator:
    image: "octopussamples/workflowbuildertemplategenerator"
    ports:
      - "4000:4000"
  auditdb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'audit'
      MYSQL_USER: 'audits'
      MYSQL_PASSWORD: 'Password01!'
      MYSQL_ROOT_PASSWORD: 'Password01!'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  audit:
    image: "octopussamples/auditsservice"
    ports:
      - "10000:8083"
    depends_on:
      - "auditdb"
    environment:
      - DATABASE_HOSTNAME=auditdb
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=audits
      - DATABASE_PASSWORD=Password01!
      - COGNITO_DISABLE_AUTH=true
      - MIGRATE_AT_START=true
    command: ["./wait-for-it.sh", "auditdb:3306", "--strict", "--", "./application", "-Dquarkus.http.host=0.0.0.0"]
  repocreator:
    image: "octopussamples/githubrepocreator"
    ports:
      - "11000:13000"
    environment:
      - COGNITO_DISABLE_AUTH=true
      - GITHUB_ENCRYPTION=9YhZbd1V3dWwgshtm5XXmGpN83JNTuv1
      - GITHUB_SALT=9jjX1i7VxlPptBdw5EqJuC2AK058qYxe
      - REPO_POPULATOR=http://repocreator:11000
      - TEMPLATE_GENERATOR=http://templategenerator:4000
      - AUDIT_SERVICE=http://audits:10000
      # Create this key with:
      # openssl req  -nodes -new -x509  -keyout server.key -out server.cert
      # cat server.key | base64 -w0
      - CLIENT_PRIVATE_KEY=LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQ21aekZtOEgrdzNZdG8KSGg5czJsc0hvOUp1M1pXM0NSdHpVbHVxTEY5MGVNVERZOEFXTG5sVDFXR2EzSmpOaHQvcnRFUXhBWFNuS083WQpxcXdRWjlPKzhyTjFtdXlZS09ZYU9yOGVTUUJOSE9uZGxVb0UrSTYxSHdPTkpjK2hENVdIOW5KTmJzem5kRzJNCnIrSGd4NjlWUmtZOHhRQzBsd2NKQ1dJaHdRdWYzd3J5T3hqWVJvQkVWbzJMV2ZvY1Z2K0ZRTCtxTG9uM3RIYzEKOVNxUVlMWXMxbysxVGJOOGRnL1pkcVFhcjNqdzl3VElob0ZqZEFmUnZidzBLSHdSWmplQ2d1M1ZYSkdHMld1ZAoweG1uSm0rMUhkYkQ5eitZaTQzbWtiQnBFYXc4Y25lZ2NIcm9sK0R3OForUExTVU1DUTBVNm9MbFN4REExNVU2CnlHZlZlRGtsQWdNQkFBRUNnZ0VBSUpnVCtDcmhpQjVOSVM3TlR3QVNWcFBETTA0WjlrbEZaRGhjbGgrczd0NTkKQkJ5MDBtTjJCbkxFZEpZREpEYm9BMzVDNFNwODFBVlRpNE1hd3ZmalpRS2JIazBqVE1hdUU3TXdIbG1FUXBhSQpSSXZxZk1ESEN6a3c4K1BWSUtJeDB2ajErSzdjV2ZYWFEzaHNFU0JyK3BNU1RQTDFxV252eWRoWnJXem52ditiCmdVb1EzRmhBcGViRi9kQUN2RkU1Qzk2Vmw1bzhCbm1xS0VTd0I3bUJ2OFJCdmo3S0hhbWhvbCtlM0tCMFlLUisKUHZQVW5RdTB2aUZvQWhUczVJaWlFckx6ZVZKUnF4dFdmbFlNRGdWWmsxSHRwMFByYmtPWGk0dXBvMDRGVzI5egpIL0lHYkx2dWp6dU0zMFlBWHMrTG1iSWpYbXlRd2pHVEdnaDRjWlFxZ1FLQmdRRFNYbTZ1OWFVS3pHb1hRVitjCkxtbExFTlV6bk92UUd0bzRjMUx3WFovWlJ0RVRXVTRCanFvMnVRRDEwQWRLZVllVWVaeHNSMFF6T2JpK2Vlb1oKMEI1djBiaVVNVFprK2YwdVR5bEJ5NmJEczYxdC8wbWlEMVNXVndnMHJhbjFXQytOU2RaYVJhd1ZTem9IWUc1cAp0Y0cxU2UvSUtHSWxVR2F6NXpPZlhzUm1oUUtCZ1FES2YyTFY5dk1mZVZUSVhDcFdXRU1TSkdEOUJZR3I2S29oCnI0Z3lWUzdnR3BIRkk1SStnM0xoSDZNUW4xaUlHd0ZNbjF3OXZES3FubEY4dXdydTNBQ3NaeDkxN3hpN3F3TlYKbjU1ZVdPaDZIYzZZOXcrald3SUJBcmhONTdsT0trMkRkNzVHalRkNGkxVE1Sb251ZVJSc0FuYlpjQnozTUtpYworTS9uRXYrYUlRS0JnUUNOOUtzNzVRYzZBamFVK3NoSjNBZXhYK3ArcWFWM0NLZTQ4QmxIbWVZRCtJV2RTT1lhCnB1cTFncUhqUGoydFE5VDVuQmF4K21WTEsrZytvSVlZWlJnazNLQnhYOFFVMzV5NVl6R3o5SGpVRnFzeFR0T2gKU0RjTVBDNk5YYU1TckM5cWFDajlRWWFkMStXUWxNSHRFM2xqbkVEeUVFNHFYOWJ1RDFZR2RTeVRBUUtCZ0VEdQp2aXVzSjJQRlRVbCtQRms1cmpBb0dDMnFVVjFsbXdCNFArMGI0WThkRmZjb0krSUYxcFdYeG5zekRYbC9aMWhCCmxadDZPS2o3WVZma3htbTNoRVBFUVpOWW13NjZsTFFsSGV4VkNCNzRaZUlvL3d1N3lCVzQ0STZpcW9vRkNKd0sKanFvaTZGR3dJLzNvOUp2U21aalU1WFZ0L092SzM1YU9ObVI3ZEJqaEFvR0JBTFhHK2VLV0swdEUwSWFnSWN5YQpqaHNiT0Z3dSsxNjNNb0xkaXpXU1JDMUYzTHY3K0ptN1ZSWVJTbDM2cXMyOC9RUW4rYXMxQ2FhV1BtZ3BnY3BoClB6ZDNONnRTUEN2a1FuQjNkMVFwVjZiaExnODdlcDdLajlkaDUzWnY3ZDVtcUY5RCt2SDRhelNDakRQRXU5eE8KZnJGTVIwY2JxY2Z5MDRsUFNtRW4zRHBOCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
  repoproxy:
    image: "octopussamples/githubrepoproxy"
    ports:
      - "12000:8083"
    environment:
      - COGNITO_DISABLE_AUTH=true
      - GITHUB_ENCRYPTION=9YhZbd1V3dWwgshtm5XXmGpN83JNTuv1
      - GITHUB_SALT=9jjX1i7VxlPptBdw5EqJuC2AK058qYxe
  octopusproxy:
    image: "octopussamples/octopusproxy"
    ports:
      - "13000:8083"
    environment:
      - COGNITO_DISABLE_AUTH=true
  githuboauth:
    image: "octopussamples/githuboauthbackend"
    ports:
      - "14000:9000"
    environment:
      - GITHUB_REDIRECT=http://localhost:5000
      - GITHUB_LOGIN_REDIRECT=http://localhost:14000/oauth/github/code
      - GITHUB_OAUTH_APP_CLIENT_ID
      - GITHUB_OAUTH_APP_CLIENT_SECRET
      - GITHUB_ENCRYPTION=9YhZbd1V3dWwgshtm5XXmGpN83JNTuv1
      - GITHUB_SALT=9jjX1i7VxlPptBdw5EqJuC2AK058qYxe
      - LAMBDA_HANDLER=thisvalueisunused
      

      

