version: "3.9"
services:
  frontend:
    image: "octopussamples/workflowbuilderfrontend"
    ports:
      - "5000:5000"
    volumes:
      # This configuration file is used to customize the frontend web application.
      - ${PWD}/config.json:/workspace/build/config.json
      # This public key is the public half of the key pair referenced by repocreator.
      - ${PWD}/public_key.pem:/workspace/build/public_key.pem
  templategenerator:
    image: "octopussamples/workflowbuildertemplategenerator"
    ports:
      - "4000:4000"
    expose:
      - "4000"
  auditdb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'audit'
      MYSQL_USER: 'audits'
      MYSQL_PASSWORD: 'Password01!'
      MYSQL_ROOT_PASSWORD: 'Password01!'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  audit:
    image: "octopussamples/auditsservice"
    ports:
      - "10000:10000"
    depends_on:
      - "auditdb"
    environment:
      - DATABASE_HOSTNAME=auditdb
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=audits
      - DATABASE_PASSWORD=Password01!
      - COGNITO_DISABLE_AUTH=true
      - MIGRATE_AT_START=true
    command: ["./wait-for-it.sh", "auditdb:3306", "--strict", "--", "./application", "-Dquarkus.http.host=0.0.0.0"]
  repocreator:
    image: "octopussamples/githubrepocreator"
    ports:
      - "11000:11000"
    expose:
      - "10000"
    environment:
      - COGNITO_DISABLE_AUTH=true
      - GITHUB_ENCRYPTION=9YhZbd1V3dWwgshtm5XXmGpN83JNTuv1
      - GITHUB_SALT=9jjX1i7VxlPptBdw5EqJuC2AK058qYxe
      - REPO_POPULATOR=http://repocreator:11000
      - TEMPLATE_GENERATOR=http://templategenerator:4000
      - AUDIT_SERVICE=http://audit:10000
      # Create this key with:
      # openssl req  -nodes -new -x509  -keyout server.key -out server.cert
      # Convert pem to der:
      # openssl x509 -outform der -in server.cert -out server.der
      # Base 64 encode the private key with this command. The CLIENT_PRIVATE_KEY env var is the output of this command:
      # cat server.der | base64 -w0
      # Extract the public key (for use with frontend) with:
      # openssl x509 -pubkey -noout -in cert.pem  > public_key.pem
      - CLIENT_PRIVATE_KEY=MIIDazCCAlOgAwIBAgIUecZhj6iXleyArVqj92ertj3oeVQwDQYJKoZIhvcNAQELBQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoMGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAeFw0yMjA2MjIwMDI0MjFaFw0yMjA3MjIwMDI0MjFaMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCmZzFm8H+w3YtoHh9s2lsHo9Ju3ZW3CRtzUluqLF90eMTDY8AWLnlT1WGa3JjNht/rtEQxAXSnKO7YqqwQZ9O+8rN1muyYKOYaOr8eSQBNHOndlUoE+I61HwONJc+hD5WH9nJNbszndG2Mr+Hgx69VRkY8xQC0lwcJCWIhwQuf3wryOxjYRoBEVo2LWfocVv+FQL+qLon3tHc19SqQYLYs1o+1TbN8dg/ZdqQar3jw9wTIhoFjdAfRvbw0KHwRZjeCgu3VXJGG2Wud0xmnJm+1HdbD9z+Yi43mkbBpEaw8cnegcHrol+Dw8Z+PLSUMCQ0U6oLlSxDA15U6yGfVeDklAgMBAAGjUzBRMB0GA1UdDgQWBBQmMYRY46VEXqOh/Fxkl204LCXVRTAfBgNVHSMEGDAWgBQmMYRY46VEXqOh/Fxkl204LCXVRTAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQCDtnhi/ONpbxQe1quNDDWSQ6vfDcMPeyOxVcyzJ3W3qo6E7vHPvWYNZIsclPLXmjWGivDA+FGBXpdn0IDpEzN9ze7EvRC3erVDnBjPrafBUplcddb6CMYRtN00KvK6Ibsv6zsem2Kj3UfhYIAch7w2dQqyhlbGb6uVWwIALq9yFC1Z4z/2hDl/mESMLA1bySY80j46zIfe4zjopm+X43DeMVuPFqhGX9pblCduJ3VB0YnbSNYymas4Z5OxKQEqw5H+oWUZnFBlk8wEvZHqxiSROpiFgTishdiV1jv2R0lm5Gj3i+29vQMfjAkqyaqAKdzamL8kES+13Z3Qq1Vg4aDC
  repoproxy:
    image: "octopussamples/githubrepoproxy"
    ports:
      - "12000:12000"
    expose:
      - "12000"      
    environment:
      - COGNITO_DISABLE_AUTH=true
      # Any random 32 chars will do, but they have to be shared with githuboauth
      - GITHUB_ENCRYPTION=9YhZbd1V3dWwgshtm5XXmGpN83JNTuv1
      # Any random 32 chars will do, but they have to be shared with githuboauth
      - GITHUB_SALT=9jjX1i7VxlPptBdw5EqJuC2AK058qYxe
  octopusproxy:
    image: "octopussamples/octopusproxy"
    ports:
      - "13000:13000"
    expose:
      - "13000"
    environment:
      - COGNITO_DISABLE_AUTH=true
  githuboauth:
    image: "octopussamples/githuboauthbackend"
    ports:
      - "14000:14000"
    expose:
      - "14000"
    environment:
      - GITHUB_REDIRECT=http://localhost:5000
      - GITHUB_LOGIN_REDIRECT=http://localhost:14000/oauth/github/code
      # Create a GitHub Oauth app and set the following env vars to the client ID and secret 
      - GITHUB_OAUTH_APP_CLIENT_ID
      - GITHUB_OAUTH_APP_CLIENT_SECRET
      # Any random 32 chars will do, but they have to be shared with repoproxy
      - GITHUB_ENCRYPTION=9YhZbd1V3dWwgshtm5XXmGpN83JNTuv1
      # Any random 32 chars will do, but they have to be shared with repoproxy
      - GITHUB_SALT=9jjX1i7VxlPptBdw5EqJuC2AK058qYxe
      # This value is not used, but must still be defined
      - LAMBDA_HANDLER=thisvalueisunused
      

      

