name: EKS Deployment
'on':
  workflow_dispatch: {}
  push:
    paths:
      - '**/*'
      - '!.github/badges/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # This main workflow file implements each stage through composable actions -
      # https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
      # This allows us to mix and match build and deployment steps, which is important for a platform engineering tool
      # like the App Builder.

      - name: Create Initial Space
        id: shared_space
        uses: ./github/shared-space
        with:
          octopus_server: ${{ secrets.OCTOPUS_SERVER }}
          octopus_apikey: ${{ secrets.OCTOPUS_APIKEY }}
          octopus_space: "<%= octopus_space %>"
          octopus_user_id: "<%= octopus_user_id %>"
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          terraform_bucket_suffix: ${{ secrets.TERRAFORM_BUCKET_SUFFIX }}
          terraform_bucket_region: ${{ secrets.TERRAFORM_BUCKET_REGION }}
          github_repo: ${{ github.repository }}
          github_repo_owner: ${{ github.repository_owner }}

      - name: Create Shared Resources
        id: shared_resources
        uses: ./github/shared-infrastructure
        with:
          octopus_server: ${{ secrets.OCTOPUS_SERVER }}
          octopus_apikey: ${{ secrets.OCTOPUS_APIKEY }}
          octopus_space_id: ${{ steps.shared_space.outputs.octopus_space_id }}
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: "<%= aws_region %>"
          github_username: ${{ github.actor }}
          github_repo: ${{ github.repository }}
          terraform_bucket_suffix: ${{ secrets.TERRAFORM_BUCKET_SUFFIX }}
          terraform_bucket_region: ${{ secrets.TERRAFORM_BUCKET_REGION }}

      - name: Create the ECR repository and feed
        id: ecr_resources
        uses: ./github/aws-ecr
        with:
          octopus_server: ${{ secrets.OCTOPUS_SERVER }}
          octopus_apikey: ${{ secrets.OCTOPUS_APIKEY }}
          octopus_space_id: ${{ steps.shared_space.outputs.octopus_space_id }}
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: "<%= aws_region %>"
          aws_ecr_repository_name: "octopus-microservice-<%= framework.toLowerCase() %>-<%= platform.toLowerCase() %>"
          terraform_bucket_suffix: ${{ secrets.TERRAFORM_BUCKET_SUFFIX }}
          terraform_bucket_region: ${{ secrets.TERRAFORM_BUCKET_REGION }}
          github_repo: ${{ github.repository }}

      - name: Build Java Microservice
        uses: ./github/java-microservice
        with:
          image_tag: ${{ steps.ecr_resources.outputs.aws_ecr_repository_url }}
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: "<%= aws_region %>"
          octopus_server: ${{ secrets.OCTOPUS_SERVER }}
          octopus_apikey: ${{ secrets.OCTOPUS_APIKEY }}
          octopus_space_id: ${{ steps.shared_space.outputs.octopus_space_id }}
          run_number: ${{ github.run_number }}
          octopus_space: ${{ steps.shared_space.outputs.octopus_space_name }}
          github_repo: ${{ github.repository }}

      - name: Create Kubernetes Deployment Project
        uses: ./github/kubernetes-deployment
        with:
          octopus_server: ${{ secrets.OCTOPUS_SERVER }}
          octopus_apikey: ${{ secrets.OCTOPUS_APIKEY }}
          octopus_space_id: ${{ steps.shared_space.outputs.octopus_space_id }}
          octopus_space: ${{ steps.shared_space.outputs.octopus_space_name }}
          octopus_dockerhub_feed_id: ${{ steps.shared_resources.outputs.octopus_dockerhub_feed_id }}
          octopus_k8s_feed_id: ${{ steps.ecr_resources.outputs.ecr_feed_id }}
          octopus_application_lifecycle_id: ${{ steps.shared_resources.outputs.application_lifecycle_id }}
          octopus_infrastructure_lifecycle_id: ${{ steps.shared_resources.outputs.infrastructure_lifecycle_id }}
          octopus_docker_image: "octopus-microservice-<%= framework.toLowerCase() %>-<%= platform.toLowerCase() %>"
          octopus_library_variable_set_id: ${{ steps.shared_resources.outputs.octopus_library_variable_set_id }}
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: "<%= aws_region %>"
          repository_owner: ${{ github.repository_owner }}
          octopus_aws_account_id: ${{ steps.shared_resources.outputs.aws_account_id }}
          terraform_bucket_suffix: ${{ secrets.TERRAFORM_BUCKET_SUFFIX }}
          terraform_bucket_region: ${{ secrets.TERRAFORM_BUCKET_REGION }}
          github_repo: ${{ github.repository }}
