# build stage
FROM golang:alpine AS build-env
ADD . /src
RUN cd /src && go build cmd/web/main.go

# final stage
FROM public.ecr.aws/lambda/provided:al2
COPY --from=build-env /src/main /main
ENTRYPOINT [ "/main" ]