version: "3.9"
services:
  frontend:
    image: "octopussamples/frontend-webapp"
    pull_policy: always
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ${PWD}/config.json:/workspace/build/config.json
  product_service:
    image: "octopussamples/product-service"
    pull_policy: always
    ports:
      - "127.0.0.1:8083:8083"
    expose:
      - "8083"
