version: "3.9"
services:
  frontend:
    image: "octopussamples/frontend-webapp"
    pull_policy: always
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ${PWD}/config.json:/workspace/build/config.json
  product_service:
    image: "octopussamples/product-service-mysql"
    pull_policy: always
    ports:
      - "127.0.0.1:8083:8083"
    expose:
      - "8083"
    environment:
      DATABASE_HOSTNAME: 'db'
      DATABASE_USERNAME: 'product'
      DATABASE_PASSWORD: 'password'
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'product'      
      MYSQL_USER: 'product'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    expose:
      - '3306'
    healthcheck:
      test: mysqladmin ping -h db -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 5s
      retries: 12
