version: "3.9"
services:
  frontend:
    image: "octopussamples/customizableworkflowbuilderfrontend"
    pull_policy: always
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ${PWD}/cards:/workspace/dist/cards
      - ${PWD}/config.json:/workspace/dist/config.json
  templategenerator:
    image: "octopussamples/workflowbuildertemplategenerator"
    pull_policy: always
    ports:
      - "127.0.0.1:4000:4000"
    expose:
      - "4000"
    environment:
      # UNSAFE_ENABLE_NPM_INSTALL is unsafe because it allows any random generator to be downloaded and run.
      # Generators are just JavaScript code, which can do literally anything. UNSAFE_ENABLE_NPM_INSTALL should
      # only be enabled for testing.
      # The preferred solution to including new generators is to install them directly into the Docker image
      # using "npm -i --no-save generator-<generatorname>".
      - UNSAFE_ENABLE_NPM_INSTALL=true
      

