name: <%= project_name %>

on:
  push:
    paths:
      - '.github/workflows/<%= project_name %>.yaml'
      - 'terraform/<%= project_name %>/**'
      - 'github/<%= project_name %>/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build
        uses: ./github/<%= project_name %>
        with:
          github_app_id: <%= github_app_id %>
          github_installation_id: <%= github_installation_id %>
          github_pem_file: <%= github_pem_file %>
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_name: <%= project_name %>
          project_directory_name: <%= project_name %>
          octopus_server: <%= octopus_server %>
          octopus_apikey: <%= octopus_apikey %>
          octopus_space_id: <%= octopus_space_id %>
          octopus_development_app_environment_name: <%= octopus_development_app_environment_name %>
          octopus_development_app_environment_exists: <%= octopus_development_app_environment_exists %>
          octopus_development_security_environment_name: <%= octopus_development_security_environment_name %>
          octopus_production_app_environment_name: <%= octopus_production_app_environment_name %>
          octopus_production_app_environment_exists: <%= octopus_production_app_environment_exists %>
          octopus_production_security_environment_name: <%= octopus_production_security_environment_name %>
          octopus_administration_environment_name: <%= octopus_administration_environment_name %>

          # AWS vars
          aws_access_key: <%= aws_access_key %>
          aws_secret_key: <%= aws_secret_key %>
          aws_region: <%= aws_region %>