name: <%= project_name %>

on:
  push:
    paths:
      - '.github/workflows/<%= project_name %>.yaml'
      - 'terraform/<%= project_name %>/**'
      - 'github/<%= project_name %>/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build
        uses: ./github/<%= project_name %>
        with:
          github_app_id: <%= github_app_id %>
          github_installation_id: <%= github_installation_id %>
          github_pem_file: <%= github_pem_file %>
          project_name: <%= project_name %>
          project_directory_name: <%= project_name %>
          octopus_server: <%= octopus_server %>
          octopus_apikey: <%= octopus_apikey %>
          octopus_space_id: <%= octopus_space_id %>
          dockerhub_username: <%= dockerhub_username %>
          dockerhub_password: <%= dockerhub_password %>
          existing_dockerhub_feed: <%= existing_dockerhub_feed %>
          dockerhub_feed_name: <%= dockerhub_feed_name %>

          # AWS vars
          aws_access_key: <%= aws_access_key %>
          aws_secret_key: <%= aws_secret_key %>
          aws_region: <%= aws_region %>