name: <%= project_name %>

on:
  push:
    paths:
      - '.github/workflows/<%= project_name %>.yaml'
      - 'terraform/<%= project_name %>/**'
      - 'github/<%= project_name %>/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build
        uses: ./github/<%= project_name %>
        with:
          github_app_id: <%= github_app_id %>
          github_installation_id: <%= github_installation_id %>
          github_pem_file: <%= github_pem_file %>
          project_name: <%= project_name %>
          project_directory_name: <%= project_name %>
          octopus_server: <%= octopus_server %>
          octopus_apikey: <%= octopus_apikey %>
          octopus_space_id: <%= octopus_space_id %>
          development_environment_id: <%= development_environment_id %>
          development_security_environment: <%= development_security_environment %>
          production_environment_id: <%= production_environment_id %>
          production_security_environment: <%= production_security_environment %>

          # AWS vars
          aws_access_key: <%= aws_access_key %>
          aws_secret_key: <%= aws_secret_key %>
          aws_region: <%= aws_region %>

          # Azure vars
          development_azure_application_id: <%= development_azure_application_id %>
          development_azure_password: <%= development_azure_password %>
          development_azure_subscription_id: <%= development_azure_subscription_id %>
          development_azure_tenant_id: <%= development_azure_tenant_id %>

          production_azure_application_id: <%= production_azure_application_id %>
          production_azure_password: <%= production_azure_password %>
          production_azure_subscription_id: <%= production_azure_subscription_id %>
          production_azure_tenant_id: <%= production_azure_tenant_id %>