name: 'Octopus proxy'
description: Build and deploy the Octopus proxy
inputs:
  dockerhub_username:
    required: true
    description: The DockerHub username
  dockerhub_password:
    required: true
    description: The DockerHub Password
  github_token:
    required: true
    description: The GitHub token
  octopus_server_url:
    required: true
    description: The Octopus server url
  octopus_api_token:
    required: true
    description: The Octopus API token
  run_number:
    required: true
    description: The GitHub Actions run number
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_password }}

    - uses: nelonoel/branch-name@v1.0.1

    - name: Install Octopus CLI
      uses: OctopusDeploy/install-octopus-cli-action@v1.1.1
      with:
        version: latest

    - name: Set up JDK 1.17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - uses: DeLaGuardo/setup-graalvm@4.0
      with:
        graalvm: '22.3.0'
        java: 'java17'
        arch: 'amd64'

    - name: Install native-image component
      run: gu install native-image
      shell: bash

    - name: Checkstyle
      run: ./mvnw --batch-mode checkstyle:check
      shell: bash
      working-directory: java

    - name: Install modules
      run: ./mvnw --batch-mode install -DskipTests
      shell: bash
      working-directory: java

    - name: Update version
      run: ./mvnw --batch-mode build-helper:parse-version versions:set -DnewVersion=0.1.${{ github.run_number }}
      shell: bash
      working-directory: java/octopus-proxy

    - name: List dependencies
      run: ./mvnw --batch-mode dependency:tree --no-transfer-progress
      shell: bash
      working-directory: java/octopus-proxy

    - name: Build with Maven for web
      run: ./mvnw --batch-mode clean package --file pom.xml -Pnative -DskipTests "-Dquarkus.profile=prod"
      shell: bash
      working-directory: java/octopus-proxy

    - name: Build Docker Image
      run: |
        docker build -f src/main/docker/Dockerfile.native-distroless -t octopussamples/octopusproxy:1.0.${{ inputs.run_number }}${{ env.PRERELEASE }} .
        docker push octopussamples/octopusproxy:1.0.${{ inputs.run_number }}${{ env.PRERELEASE }}
        docker image tag octopussamples/octopusproxy:1.0.${{ inputs.run_number }}${{ env.PRERELEASE }} octopussamples/octopusproxy
        docker push octopussamples/octopusproxy
      shell: bash
      working-directory: java/octopus-proxy

    - name: Build with Maven for lambda
      run: ./mvnw --batch-mode clean package --file pom.xml -Pnative -Plambda -DskipTests "-Dquarkus.profile=prod"
      shell: bash
      working-directory: java/octopus-proxy

    - name: Test Backend
      run: ./mvnw --batch-mode test
      shell: bash
      working-directory: java/octopus-proxy

    - name: Generate JaCoCo Badges
      id: jacocoMod1
      uses: cicirello/jacoco-badge-generator@v2.8.1
      with:
        generate-branches-badge: true
        jacoco-csv-file: java/octopus-proxy/target/jacoco-report/jacoco.csv
        coverage-badge-filename: octopusproxy.svg
        branches-badge-filename: octopusproxybranches.svg

    - name: Update resources
      if: ${{ env.BRANCH_NAME == 'main' }}
      uses: test-room-7/action-update-file@v1.6.0
      with:
        file-path: |
          .github/badges/octopusproxy.svg
          .github/badges/octopusproxybranches.svg
        commit-msg: Update badges
        github-token: ${{ inputs.github_token }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        tag_name: octopus-proxy.0.1.${{ inputs.run_number }}
        release_name: Octopus Proxy Release 0.1.${{ inputs.run_number }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: java/octopus-proxy/target/octopus-proxy-runner
        asset_name: octopus-proxy-runner
        asset_content_type: application/octet-stream

    - name: Rename zip
      run: >
        mv octopus-proxy/target/function.zip
        octopus-proxy-lambda.0.1.${{ inputs.run_number }}.zip
      shell: bash
      working-directory: java

    - name: Push Package
      run: >
        octo push --package octopus-proxy-lambda.0.1.${{ inputs.run_number }}.zip
        --server ${{ inputs.octopus_server_url }}
        --apiKey ${{ inputs.octopus_api_token }}
        --space "Content Team"
      shell: bash
      working-directory: java

    - name: Generate SBOM
      run: ./mvnw cyclonedx:makeAggregateBom -DskipTests --no-transfer-progress --batch-mode
      shell: bash
      working-directory: java

    - name: Build SBOM package
      run: >
        octo pack
        --id octopus-proxy-lambda-sbom
        --version 0.1.${{ inputs.run_number }}
        --format zip
        --include **/bom.xml
      shell: bash
      working-directory: java

    - name: Push SBOM Package
      run: >
        octo push --package octopus-proxy-lambda-sbom.0.1.${{ inputs.run_number }}.zip
        --server ${{ inputs.octopus_server_url }}
        --apiKey ${{ inputs.octopus_api_token }}
        --space "Content Team"
      shell: bash
      working-directory: java

    - name: Generate Octopus Deploy build information
      uses: xo-energy/action-octopus-build-information@v1.1.2
      with:
        octopus_api_key: ${{ inputs.octopus_api_token }}
        octopus_project: Deploy Octopus Service Account Creator
        octopus_server: ${{ inputs.octopus_server_url }}
        octopus_space: Content Team
        push_version: 0.1.${{ inputs.run_number }}
        push_package_ids: octopus-proxy-lambda
        push_overwrite_mode: OverwriteExisting
        output_path: octopus

    - name: Trigger deployment
      if: ${{ env.BRANCH_NAME == 'main' }}
      run: >
        octo create-release
        --project "Octopus Proxy"
        --deployTo "Development"
        --package octopus-proxy-lambda:0.1.${{ inputs.run_number }}
        --package octopus-proxy-lambda-sbom:0.1.${{ inputs.run_number }}
        --server ${{ inputs.octopus_server_url }}
        --apiKey ${{ inputs.octopus_api_token }}
        --space "Content Team"
        --waitForDeployment
        --deploymentTimeout 00:30:00
      shell: bash

    - name: Trigger deployment to security environment
      if: ${{ env.BRANCH_NAME == 'main' }}
      run: >
        octo promote-release
        --project "Octopus Proxy"
        --from "Development"
        --deployTo "Development (Security)"
        --server ${{ inputs.octopus_server_url }}
        --apiKey ${{ inputs.octopus_api_token }}
        --space "Content Team"
        --latestSuccessful
      shell: bash