name: app-builder-shared-infrastructure-octopus

on:
  push:
    paths:
    - 'terraform/app-builder-shared-infrastructure/**
    - '.github/workflows/app-builder-shared-infrastructure-octopus.yml'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: App Builder Share Network Infrastructure
        uses: ./terraform/app-builder-shared-infrastructure
        with:
          octopus_server: ${{ secrets.OCTOPUS_SERVER }}
          octopus_apikey: ${{ secrets.OCTOPUS_APIKEY }}
          octopus_space_id: Spaces-882
          octopus_worker_pool_id: WorkerPools-1282
          octopus_infrastructure_lifecycle_id: Lifecycles-2241
          octopus_development_environment_id: Environments-3322
          octopus_development_security_environment_id: Environments-3341
          octopus_production_environment_id: Environments-3342
          octopus_production_security_environment_id: Environments-3361
          octopus_development_aws_account_id: Accounts-581
          octopus_production_aws_account_id: Accounts-701
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-west-1