name: azure-servicebus-proxy

on:
  push:
      paths:
      - 'java/azure-servicebus-proxy/**'
      - 'java/github/azure-servicebus-proxy/**'
      - 'java/pom.xml'
      - 'java/microservice-utils/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build
      uses: ./java/github/azure-servicebus-proxy
      with:
        run_number: ${{ github.run_number }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dockerhub_username: ${{ secrets.DOCKERHUB_SAMPLES_USERNAME }}
        dockerhub_password: ${{ secrets.DOCKERHUB_SAMPLES_PASSWORD }}
        octopus_server_url: ${{ secrets.OCTOPUS_SERVER }}
        octopus_api_token: ${{ secrets.OCTOPUS_APIKEY }}
