name: cognito-infrastructure-octopus

on:
  push:
    paths:
    - 'terraform/cognito-infrastructure/**'
    - '.github/workflows/cognito-infrastructure-octopus.yml'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Cognito Infrastructure
        uses: ./terraform/cognito-infrastructure
        with:
          octopus_server: ${{ secrets.OCTOPUS_SERVER }}
          octopus_apikey: ${{ secrets.OCTOPUS_APIKEY }}
          octopus_space_id: Spaces-882
          # WorkerPools-1282 is Hosted Ubuntu
          octopus_worker_pool_id: WorkerPools-1301
          octopus_infrastructure_lifecycle_id: Lifecycles-2241
          octopus_development_environment_id: Environments-3322
          octopus_development_security_environment_id: Environments-3341
          octopus_production_environment_id: Environments-3342
          octopus_production_security_environment_id: Environments-3361
          octopus_development_aws_account_id: Accounts-581
          octopus_production_aws_account_id: Accounts-701
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-west-1