name: content-team-template-generator-ecr

on:
  push:
    paths:
      - '.github/workflows/content-team-template-generator-ecr.yml'
      - 'terraform/content-team-template-generator-ecr/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build
        uses: ./terraform/content-team-template-generator-ecr
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          octopus_server: ${{ secrets.OCTOPUS_SERVER }}
          octopus_apikey: ${{ secrets.OCTOPUS_APIKEY }}
          octopus_space_id: ${{ secrets.OCTOPUS_SPACEID }}
          octopus_development_environment_id: ${{ secrets.OCTOPUS_DEVELOPMENT_ENVIRONMENT_ID }}
          octopus_production_environment_id: ${{ secrets.OCTOPUS_PRODUCTION_ENVIRONMENT_ID }}
          octopus_development_security_environment_id: ${{ secrets.OCTOPUS_DEVELOPMENT_SECURITY_ENVIRONMENT_ID }}
          octopus_production_security_environment_id: ${{ secrets.OCTOPUS_PRODUCTION_SECURITY_ENVIRONMENT_ID }}
          octopus_project_name: Template Generator Backend ECR
          octopus_project_group_name: Content Team Template Generator
          octopus_lifecycle_id: ${{ secrets.OCTOPUS_PRODUCTION_ONLY_LIFECYCLEID }}
          octopus_aws_development_account_id: ${{ secrets.OCTOPUS_AWS_DEVELOPMENT_ACCOUNTID }}
          octopus_aws_production_account_id: ${{ secrets.OCTOPUS_AWS_PRODUCTION_ACCOUNTID }}
          aws_region: us-west-2
          terraform_bucket_suffix: d66bfa00-e6d4-48be-89a8-e978f1e5e771
          cloudformation_stack_name: content-team-template-generator-backend
          repository_name: template-generator

