name: github-oauth-backend

on:
  push:
    paths:
    - '.github/workflows/github-oauth-backend.yml'
    - 'java/pom.xml'
    - 'java/github-oauth-backend/**'
    - 'java/microservice-utils/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      APP_GITHUB_SECRET: ${{ secrets.APP_GITHUB_SECRET }}                                                                                       
      APP_GITHUB_ID: ${{ secrets.APP_GITHUB_ID }}

    steps:
      - uses: actions/checkout@v1

      - name: Build
        uses: ./java/github/github-oauth-backend
        with:
          dockerhub_username: ${{ secrets.DOCKERHUB_SAMPLES_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKERHUB_SAMPLES_PASSWORD }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          octopus_server_url: ${{ secrets.OCTOPUS_SERVER }}
          octopus_api_token: ${{ secrets.OCTOPUS_APIKEY }}
          run_number: ${{ github.run_number }}
          oauth_client_id: ${{ secrets.OAUTH_CLIENT_ID }}
          oauth_client_secret: ${{ secrets.OAUTH_CLIENT_SECRET }}
            