name: octopus-service-account-creator

on:
  push:
    paths:
    - 'java/octopus-service-account-creator/**'
    - '.github/workflows/octopus-service-account-creator.yml'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build
        uses: ./java/github/octopus-service-account-creator
        with:
          octopus_server_url: ${{ secrets.OCTOPUS_SERVER }}
          octopus_api_token: ${{ secrets.OCTOPUS_APIKEY }}
          run_number: ${{ github.run_number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerhub_username: ${{ secrets.DOCKERHUB_SAMPLES_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKERHUB_SAMPLES_PASSWORD }}