# Builds the sample Javascript frontend embedded in the Yeoman template as a Docker image and
# publishes it to DockerHub.

name: Sample frontend webapp Docker build
on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest    
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
         username: ${{ secrets.DOCKERHUB_SAMPLES_USERNAME }}
         password: ${{ secrets.DOCKERHUB_SAMPLES_PASSWORD }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: update version
        run: cat <<< "$(jq '.frontendVersion = "v0.1.${{ github.run_number }}"' js/generator-octopus-javascript-frontend/generators/app/templates/js/frontend/public/config.json)" > js/generator-octopus-javascript-frontend/generators/app/templates/js/frontend/public/config.json
        shell: bash
      - name: Build latest image
        uses: mamezou-tech/buildpacks-action@master
        with:
          image: 'octopussamples/frontend-webapp'
          tag: 'latest'
          path: 'js/generator-octopus-javascript-frontend/generators/app/templates/js/frontend'
          builder: 'heroku/buildpacks:20'
          buildpacks: 'heroku/nodejs https://cnb-shim.herokuapp.com/v1/heroku-community/static'
          env: NODE_OPTIONS=--openssl-legacy-provider
      - name: Push to DockerHub
        run: |
          docker push octopussamples/frontend-webapp
          docker image tag octopussamples/frontend-webapp octopussamples/frontend-webapp:v0.1.${{ github.run_number }}
          docker push octopussamples/frontend-webapp:v0.1.${{ github.run_number }}
        shell: bash    
