# Builds the sample product Java app embedded in the Yeoman template as a Docker image and
# publishes it to DockerHub.

name: Sample product service Docker build
on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest    
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
         username: ${{ secrets.DOCKERHUB_SAMPLES_USERNAME }}
         password: ${{ secrets.DOCKERHUB_SAMPLES_PASSWORD }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build with Maven
        run: ./mvnw --batch-mode package --file pom.xml
        shell: bash
        working-directory: js/generator-octopus-java-microservice/generators/app/templates/java
      - name: Push to DockerHub
        run: |
          docker build -f src/main/docker/Dockerfile.legacy-jar -t octopussamples/product-service .
          docker push octopussamples/product-service
        shell: bash
        working-directory: js/generator-octopus-java-microservice/generators/app/templates/java/products-microservice   
      - name: Build with MySQL support with Maven
        run: ./mvnw --batch-mode package --file pom.xml -Dquarkus.profile=mysql
        shell: bash
        working-directory: js/generator-octopus-java-microservice/generators/app/templates/java
      - name: Push to DockerHub
        run: |
          docker build -f src/main/docker/Dockerfile.legacy-jar -t octopussamples/product-service-mysql .
          docker push octopussamples/product-service-mysql
          docker image tag octopussamples/product-service-mysql octopussamples/product-service-mysql:v0.1.${{ github.run_number }}
          docker push octopussamples/product-service-mysql:v1.0.${{ github.run_number }}
        shell: bash
        working-directory: js/generator-octopus-java-microservice/generators/app/templates/java/products-microservice    
