# Builds the sample product Java app embedded in the Yeoman template as a Lambda and
# publishes it to the github maven feed.

name: Sample product service Lambda build
on:
  push:
    branches: main

permissions:
  packages: write

jobs:
  login:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build with Maven
        run: ./mvnw -P "native,lambda" --batch-mode package --file pom.xml
        shell: bash
        working-directory: js/generator-octopus-java-microservice/generators/app/templates/java
      - name: Create Serverless Package
        run: zip products-service-lambda.zip serverless.yaml target/function.zip
        shell: bash
        working-directory: js/generator-octopus-java-microservice/generators/app/templates/java/products-microservice
      - name: Push package to Maven feed
        run: >
          ./mvnw deploy:deploy-file
          -Dfile=products-service-lambda.zip
          -DgroupId=com.octopus
          -DartifactId=products-service-lambda
          -Dversion=1.0.${{ github.run_number }}
          -Dpackaging=zip
          -Durl="https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@maven.pkg.github.com/${{ github.repository }}"
        shell: bash
        working-directory: js/generator-octopus-java-microservice/generators/app/templates/java/products-microservice
